Repository usi-sweet-sure/EnsuredEnergy, pull requests merged in 2023-07, with the labels that each got.

#15 [WIP] Basic Energy Management Systems
  project.godot
  scenes/demo/BuildMenu.tscn
  scenes/demo/energy_bar.tscn
  scenes/demo/main_demo.tscn
  scenes/demo/world.tscn
  src/cs/GameLoop.cs
  src/cs/building/BuildButton.cs
  src/cs/building/PowerPlant.cs
  src/cs/resources/EnergyManager.cs
  src/cs/resources/EnvironmentManager.cs
  src/cs/resources/ResourceManager.cs
  src/cs/resources/SupportManager.cs
  src/cs/ui/InfoBar.cs
  src/cs/ui/UI.cs
  sure_energy_tycoon.csproj
Labels: Demo

#19 Energy Systems UI bufixes
  scenes/demo/BuildMenu.tscn
  scenes/demo/build_button.tscn
  scenes/demo/energy_bar.tscn
  scenes/demo/farm.tscn
  scenes/demo/power_plant.tscn
  scenes/demo/shock.tscn
  scenes/demo/ui.tscn
  src/cs/GameLoop.cs
  src/cs/building/BuildButton.cs
  src/cs/building/BuildMenu.cs
  src/cs/building/PowerPlant.cs
  src/cs/resources/EnergyManager.cs
  src/cs/resources/ResourceManager.cs
Labels: bug

#29 Show power plant prices
  scenes/demo/power_plant.tscn
  src/cs/building/PowerPlant.cs
  src/cs/ui/InfoBar.cs
Labels: UI
